{
    "name": "School Core",
    "version": "18.0.1.0.0",
    "category": "Education",
    "summary": "Core School Management Features",
    "depends": ["base", "mail", "contacts", "hr"],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/school_menu.xml",
        "views/student_views.xml",
        "views/parent_views.xml",
        "views/teacher_views.xml",
        "views/grade_views.xml",
        "views/section_views.xml",
        "views/subject_views.xml",
        "views/subject_assignment_views.xml",
        "views/academic_year_views.xml",
    ],
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}
